ATIVOS = [
    "BTC-USD","ETH-USD","USDT-USD","BNB-USD","XRP-USD","ADA-USD",
    "AAPL","MSFT","AMZN","GOOGL","TSLA","NVDA","META","BRK-B",
    "JPM","V","MA","UNH","DIS","PG","KO","PEP","INTC","CSCO",
    "XOM","CVX","BAC","WMT","HD","VZ","ADBE"
]

INTERVALO_MINUTOS = 720
NEWS_ATIVAS = True
CANAL_ANALISE = None
CANAL_NOTICIAS = None
